Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : media ( Calcular media )
// Autor(a)    : Josué lima
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
  x,y,z,media:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("x")
Leia(x)
Escreva("y")
Leia(y)
Escreva("z")
Leia(z)
media<-(x+y+z)/3

Escreva(media)
Fimalgoritmo