Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Perimetro de uma Circunferiencia ( Calcular Perimetro )
// Autor(a)    : Josué lima
// Data atual  : 24/07/2017
Var
// Seção de Declarações das variáveis 
raio,perimetro:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("raio")
Leia(raio)
perimetro<-2*3,14*raio

Escreva(perimetro)
Fimalgoritmo